services:
    rj_frontend.templating.package.path:
        class: Rj\FrontendBundle\Templating\PathPackage
        public: false

    rj_frontend.templating.package.url:
        class: Rj\FrontendBundle\Templating\UrlPackage
        public: false

    rj_frontend.templating.package.fallback:
        class: Rj\FrontendBundle\Templating\FallbackPackage
        public: false
