language: php

branches:
  only:
    - master

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    # old PHP versions with and without the Asset component (introduced in 2.7)
    - php: 5.3
      env: SYMFONY_VERSION=2.3.*
    - php: 5.4
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.3
      env: SYMFONY_VERSION=2.8.*
    - php: 5.4
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    # HHVM with and without the Asset component (introduced in 2.7)
    - php: hhvm
      env: SYMFONY_VERSION=2.3.*
    - php: hhvm
      env: SYMFONY_VERSION=2.8.*
    # current PHP with all non-EOLed Symfony versions
    - php: 7.0
      env: SYMFONY_VERSION=2.3.*
    - php: 7.0
      env: SYMFONY_VERSION=2.6.*
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=dev-master
  allow_failures:
    - env: SYMFONY_VERSION=3.0.*
    - env: SYMFONY_VERSION=dev-master

before_install: ./.travis/before_install.php
install: ./.travis/install.php
script: ./.travis/script.php
after_script: ./.travis/after_script.php
